name: Autograde project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  grade-project:
    name: Autograde project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Run tests with Gradle
        run: ./gradlew test --stacktrace

      - name: Generate JaCoCo test coverage report
        run: ./gradlew jacocoTestReport --stacktrace

      - name: Extract pull request number
        uses: jwalton/gh-find-current-pr@v1
        id: pr

      - name: Run Autograding
        uses: uhafner/autograding-github-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.number }}
          checks-name: "Autograding GitHub Action"
          config: > # Override default configuration: just grade the test results
            {
              "tests": {
                "tools": [
                  {
                    "id": "test",
                    "name": "Unittests",
                    "pattern": "**/build/test-results/test/*.xml"
                  }
                ],
                "name": "JUnit",
                "skippedImpact": -1,
                "failureImpact": -5,
                "maxScore": 100
              },
              "coverage": {
                "max-coverage": 80,
                "report-file": "build/reports/jacoco/test/jacocoTestReport.xml"
              }
            }

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/jacoco/test
