name: Autograding

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
            java-version: '21'
            distribution: 'adopt'
            java-package: jdk
            architecture: x64
            check-latest: false
            server-id: github
            server-username: ${{ github.actor }}  # Use ${{ github.actor }} to get the GitHub username
            server-password: ${{ secrets.GITHUB_TOKEN }}
            overwrite-settings: true
            job-status: success

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Autograde
        uses: uhafner/autograding-github-action@v3
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          config: |
            {
              "checks": {
                "coverage": {
                  "max-coverage": 80,
                  "report-file": "build/reports/jacoco/test/jacocoTestReport.xml"
                }
              }
            }
          checks-name: "Autograding Check"
          pr-number: ${{ github.event.pull_request.number }}
          skip-annotations: "false"
          max-warning-annotations: 10
          max-coverage-annotations: 5
